# Generated by Django 5.2.9 on 2025-12-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Books', 'Books'), ('Toys', 'Toys')], max_length=50)),
                ('current_stock_level', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=10, help_text='Stock level at which to alert')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateTimeField()),
                ('total_revenue', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='forecaster.product')),
            ],
        ),
    ]
